/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e9ddff",
        "primary-fixed-dim": "#00dbe9",
        "outline": "#849495",
        "secondary": "#d1bcff",
        "background": "#131313",
        "on-tertiary": "#520071",
        "on-primary-fixed": "#002022",
        "on-surface-variant": "#b9cacb",
        "on-secondary-fixed-variant": "#5700c9",
        "tertiary-fixed-dim": "#ecb2ff",
        "on-secondary": "#3c0090",
        "tertiary-fixed": "#f8d8ff",
        "error": "#ffb4ab",
        "tertiary": "#fff2fd",
        "on-secondary-fixed": "#23005b",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        "error-container": "#93000a",
        "surface-container-highest": "#353534",
        "surface-bright": "#3a3939",
        "outline-variant": "#3b494b",
        "inverse-primary": "#006970",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#74009f",
        "on-primary": "#00363a",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed": "#320047",
        "secondary-container": "#7000ff",
        "surface-container-low": "#1c1b1b",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed-dim": "#d1bcff",
        "primary": "#dbfcff",
        "tertiary-container": "#f4ccff",
        "primary-container": "#00f0ff",
        "on-secondary-container": "#ddcdff",
        "primary-fixed": "#7df4ff",
        "on-tertiary-container": "#9900d0",
        "on-primary-container": "#006970",
        "on-error": "#690005",
        "surface-container": "#201f1f",
        "surface": "#131313",
        "on-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "on-error-container": "#ffdad6",
        "surface-tint": "#00dbe9",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#004f54"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
